### PR TITLE
Fix for "Name Space Issue of Settings.PaneIdentifier"

### LINKED ISSUE #110: Name Space Issue of Settings.PaneIdentifier
As this package name Settings, is the same as SwiftUI struct Settings.

After I renamed "Preferences.PaneIdentifier" to "Settings.PaneIdentifier", Xcode showed an error "'Settings' is ambiguous for type lookup in this context".

I tried to add another Settings prior, it didn't work. What should I do now? 

The only workaround for me is to leave  "Preferences.PaneIdentifier". The red error will turn to yellow warning. But it can build.

### PR DESCRIPTION
**Pull request by owenzhao**
Fixes #110

### CODE REVIEW

**Comment by DivineDominion** [comment]
👍 The namespacing in Swift is hit or miss, so this looks good to me as a workaround. @sindresorhus has stronger opinions on namespacing, though :)

**Comment by sindresorhus** [comment]
Wouldn't it be better to `typealias` the `Settings` enum, since then you could access anything on it. Maybe `Settings2` or something.

**Comment by DivineDominion** [comment]
The would be doable, but "`Settings2`", literally, sounds like a very ugly hack  :) 

(Only half trolling: what about the old `Preferences` which should still be unoccupied?)

**Comment by sindresorhus** [comment]
`AppSettings` 👍

**Comment by owenzhao** [comment]
If the owner wants to change the package's name, I think "SettingsUI" is better. The native on SwiftUI is Settings struct. The package is also for Settings, but not as for the model as UserDefaults, so SettingsUI is accurate.

**Comment by sindresorhus** [comment]
I'm not talking about changing the package name. Simply adding a typealias for the `Settings` enum.

**Comment by Kyle-Ye** [comment]
> I'm not talking about changing the package name. Simply adding a typealias for the `Settings` enum.

+1 for this. Currently I workaround it by using `import enum Settings.Settings` @owenzhao 

```
import enum Settings.Settings
import SwiftUI
```

**Pull request closed without merging**
