### PR TITLE
fix unexpected switching animation

### LINKED ISSUE #59: SwiftUI unexpected switching animation
I used SwiftUI to build preference panels. However, when switching tabs, the view jumps with a weird animation. I feel this is because the SwiftUI view hasn't loaded when switching.

This only happens for the first time switching.

See:
CleanShot 2020-08-05 at 12 14 29

My current workaround is to disable the animation:
```swift
_ = PreferencesWindowController(
  preferencePanes: [...],
  style: .toolbarItems,
  animated: false, // <---
  hidesToolbarForSingleItem: true
)
```

### LINKED ISSUE #60: Incorrect animation for first transition to preference pane with different width
When animating to a preference pane that has not been loaded before and has a larger width than the current pane the view is not correctly laid out initially, which causes an odd animation. The animation is correct in subsequent switches.

The example below is the example app with the width = 450 constraint removed from the Advanced tab, and the app set to open to the Advanced tab.

Screen Recording 2020-08-23 at 19 39 33 2020-08-23 19_49_52

I'm trying to figure out the exact scenarios that causes this. Starting on Accounts does not cause this same animation to happen so I'm not sure how the size change and animations are linked.

### PR DESCRIPTION
**Pull request by metacodes**
fixes #60
fixes #59

### CODE REVIEW

**Comment by metacodes** [comment]
> Thanks for working on this.
> 
> I'm still seeing the animation problem when I start on the "Accounts" tab in the Example app and then switch to the "General" tab.

You can reproduce this issue by starting on "General" tab and then switch to "Accounts" tab.  If you set `translatesAutoresizingMaskIntoConstraints` to be false, then the animation will work correctly.(Tested on macOS 13.2.1)

**Comment by sindresorhus** [comment]
Thanks ;)

**Comment by DivineDominion** [comment]
I wonder if

a) this may be too intrusive? If the view was assembled from code, this might already be `false`; but if it's from IB, could this break things?
b) we should add a comment above the new line to explain why this is needed?

**Comment by metacodes** [comment]
> I wonder if
> 
> a) this may be too intrusive? If the view was assembled from code, this might already be `false`; but if it's from IB, could this break things? b) we should add a comment above the new line to explain why this is needed?

By default, the property is set to true for any view you programmatically create. If you add views in Interface Builder, the system automatically sets this property to false.[https://developer.apple.com/documentation/uikit/uiview/1622572-translatesautoresizingmaskintoco](url)

Although it's UIView, but it seems the same to NSView.

**Pull request merged**
